# Expose the hr-web-app created in the previous task as a service named hr-web-app-service, accessible on port 30082 on the nodes of the cluster.
# The web application listens on port 8080.
# Name: hr-web-app-service
# Type: NodePort
# Endpoints: 2
# Port: 8080
# NodePort: 30082

apiVersion: v1
kind: Service
metadata:
  name: hr-web-app-service
spec:
  selector:
    app: hr-web
  ports:
  - port: 8080
    targetPort: 8080
    nodeport: 30082

# kubectl expose deployment hr-web-app --type=NodePort --port=8080 --name=hr-web-app-service --dry-run=client -o yaml > hr-web-app-service.yaml
