# Create a POD in the finance namespace named temp-bus with the image redis:alpine.
# Name: temp-bus
# Image Name: redis:alpine

apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance
  Labels:
    app: temp
spec:
  containers:
  - name: myapp
    image: redis:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"