# Create a static pod named static-busybox on the controlplane node that uses the busybox image and the command sleep 1000.
# Name: static-busybox
# Image: busybox1

apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: busybox
      args:
        - sleep
        - 1000sec
      resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

# kubectl run --restart=Never --image=busybox static-busybox --dry-run=client -oyaml --command --sleep 1000 > /etc/kubernets/manifests/static-busybox.yaml
#kubectl edit po orange
# kubectl replace -f /tmp/kubectl-edit-xxxx.yaml--force